config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  #get 'login/login'
  resources :users do
    collection do
      post :create_confirm
      get :create_confirm, to: "users#new"
      get :search_user
    end
    member do
      get :profile, to: "users#profile"
      get :edit_profile, to: "users#edit_profile"
      post :update_profile
      get :update_profile, to: "users#edit_profile"
      get :change_password
      post :update_password
    end
  end

  resources :posts do
    collection do
      post :post_create_confirm
      get :post_create_confirm, to: "posts#new"
      get :search_post
      get :upload_csv
      post :import_csv
      get :download
    end
    member do
      get :update_confirm, to: "posts#update_confirm"
      post :update_confirm
      post :update_post
    end
  end
  resources :password_resets
  
  get 'users/new'
  get 'login', to: 'login#login'
  post 'login', to: 'login#userlogin'
  get 'logout', to: 'login#logout'
  get '/sign_up', to: 'login#sign_up'
  post '/sign_up', to: 'login#create_account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    before_create { generate_token(:auth_token) }

    before_save :email_downcase
    belongs_to :created_user, class_name: "User", foreign_key: "create_user_id"
    belongs_to :updated_user, class_name: "User", foreign_key: "updated_user_id"
    validates :name, :profile, presence: true
    validates :email, presence: true, length: { maximum: 255},
                        format: { with: Constants::VALID_EMAIL_REGEX  },
                        uniqueness: { case_sensitive: false }
    validates :password, confirmation: true, presence: true,on: :create
    has_secure_password

    def send_password_reset
        generate_token(:password_reset_token)
        self.password_reset_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver
    end
      
    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end
 
    private
 
    def email_downcase
        self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized

  # function : index
  # show user list
  # return : @users
  def index
    @users = UserService.getAllUserList
  end

  # function : new
  # show create user page
  # return : @user
  def new
    @user = User.new()
  end

  # function : show
  # show user detail
  # params : id
  # return : @user
  def show
    @user = UserService.getUserById(params[:id])
  end

  # function : create
  # create new user
  # params : user_params
  def create
    @user = User.new(user_params)

    isSaveUser = UserService.createUser(@user)
    respond_to do |format|
      if isSaveUser
        format.html { redirect_to users_path, notice: Messages::CREATE_SUCCESSFUL }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # function : create_confirm
  # confirm user create
  # params : user_params
  # return : user
  def create_confirm
    @user = User.new(user_params)
    unless @user.valid?
      render new_user_path      
    end
    if user_params.has_key?(:profile)
      dir = "#{Rails.root}/app/assets/profiles"
      FileUtils.mkdir_p(dir) unless File.directory?(dir)
      profileName = user_params[:name] + "_" + Time.now.strftime('%Y%m%d_%H%M%S') +"." + ActiveStorage::Filename.new(user_params[:profile].original_filename).extension
      File.open(Rails.root.join('app/assets/', 'images', profileName), 'wb') do |f|
        f.write(user_params[:profile].read)
      end
      @user.profile = profileName
    end
  end

  # function : profile
  # show user profile
  # params : id
  # return : @user
  def profile
    @user = UserService.getUserById(params[:id])
  end

  # form : edit_profile
  # show profile edit form
  # params : id
  # return : user_form
  def edit_profile
    @user = UserService.getUserById(params[:id])
    @profile_form = ProfileForm.new(ProfileForm.initialize(@user, :new_profile))
  end

  # function : update_profile
  # update user profile
  # params : profile_params
  def update_profile
    @profile_form = ProfileForm.new(profile_params)
    if !@profile_form.valid?
      render :edit_profile
    elsif profile_params[:new_profile].present?
      dir = "#{Rails.root}/app/assets/profiles/"
      FileUtils.mkdir_p(dir) unless File.directory?(dir)
      profilename = profile_params[:name]+ "_" + Time.now.strftime('%Y%m%d_%H%M%S') + "." + ActiveStorage::Filename.new(profile_params[:new_profile].original_filename).extension
      File.open(Rails.root.join('app/assets/', 'images', profilename ), 'wb') do |f|
          f.write(profile_params[:new_profile].read)
      end
      @profile_form.profile = profilename
      update_user_profile(@profile_form)
    else
      update_user_profile(@profile_form)
    end
  end

  # function : search user
  # search users by criteria
  # params : name, email, from date, to date
  # return : users
  def search_user
    @users = UserService.searchUser(params)
    render :index
  end

  # function : update_password
  # update password
  # params : id, password, new password
  def update_password
    user = UserService.getUserById(params[:id])
    if !user.authenticate(params[:password])
      redirect_to change_password_user_path, notice: Messages::INCORRECT_PASSWORD
    elsif  params[:new_password] != params[:new_password_confirmation]
      redirect_to change_password_user_path, notice: Messages::INCORRECT_PASSWORD_CONFIRM
    else
      isUpdatedPassword = UserService.updatePassword(user, params)
      if isUpdatedPassword
        redirect_to users_path
      else
        redirect_to change_password_user_path
      end
    end
  end

  # function : destroy
  # delete user
  # params : id
  def destroy
    UserService.deleteUser(params[:id],current_admin[:id])
    redirect_to users_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # set user params
  def user_params
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :role, :phone, :dob, :address, :profile,:create_user_id, :updated_user_id)
  end

  # set user profile params
  def profile_params
    params.require(:profile_form).permit(:id, :name, :email, :role, :phone, :dob, :address, :profile, :new_profile, :updated_user_id)
  end

  # function : update_user_profile
  # update profile
  # params : profile_form
  def update_user_profile(profile_form)
    isUpdateProfile = UserService.updateProfile(profile_form)
    if isUpdateProfile
      redirect_to users_path
    else
      asdasd
      render :edit_profile
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, url: create_confirm_users_path(@user) do |form| %>

  <div class="field form-group row">
    <%= form.label :name, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :name, class:"form-control col-sm-5" %>
    <% if @user.errors[:name].any? %>
      <span style="color:red;">Name <%= @user.errors[:name][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :email_address, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :email, class:"form-control col-sm-5" %>
    <% if @user.errors[:email].any? %>
      <span style="color:red;">Email <%= @user.errors[:email][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :password, class:"col-sm-2 col-form-label" %>
    <%= form.password_field :password, class:"form-control col-sm-5" %>
    <% if @user.errors[:password].any? %>
      <span style="color:red;">Passsword <%= @user.errors[:password][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :confirm_password, class:"col-sm-2 col-form-label" %>
    <%= form.password_field :password_confirmation, class:"form-control col-sm-5" %>
    <% if @user.errors[:password_confirmation].any? %>
      <span style="color:red;">Passsword Confirmation <%= @user.errors[:password_confirmation][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :Type, class:"col-sm-2 col-form-label" %>
    <%= form.select(:role, options_for_select(Constants::TYPES), {}, {:class => "form-control col-sm-5"})%>
  </div>

  <div class="field form-group row">
    <%= form.label :phone, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :phone, class:"form-control col-sm-5" %>
    <% if @user.errors[:phone].any? %>
      <span style="color:red;">phone <%= @user.errors[:phone][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :date_of_birth, class:"col-sm-2 col-form-label" %>
    <%= form.date_field :dob, class:"form-control col-sm-5" %>
    <% if @user.errors[:dob].any? %>
      <span style="color:red;">Date Of Birth <%= @user.errors[:dob][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :address, class:"col-sm-2 col-form-label" %>
    <%= form.text_area :address, class:"form-control col-sm-5" %>
    <% if @user.errors[:address].any? %>
      <span style="color:red;">Address <%= @user.errors[:address][0] %>
    <% end %>
  </div>

    <div class="field form-group row">
    <%= form.label :profile, class:"col-sm-2 col-form-label" %>
    <%= form.file_field :profile, class:"form-control col-sm-5", :accept => "image/x-png,image/gif,image/jpeg" %>
    <% if @user.errors[:profile].any? %>
      <span style="color:red;">Profile <%= @user.errors[:profile][0] %>
    <% end %>
  </div>
  <%= form.hidden_field :create_user_id, :value => current_admin.id%>
  <%= form.hidden_field :updated_user_id, :value => current_admin.id%>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
    <%= link_to 'Back', users_path , class:"btn btn-dark" %>
  </div>
  
<% end %>

app/views/users/_show.html.erb
<div class="modal-header">
<h5 class="modal-title">User Detail</h5>
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-4">
                <div class="form-group">
                    <div class="img text-center "><%= image_tag @user.profile, style: 'height:120px;width:auto;' %> </div>
                </div>
        </div>
        <div class="col-8">
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Name</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.name  %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Type</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.role == "0" ? 'Admin' : 'User'  %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.email  %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.phone  %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">date_of_birth</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.dob  %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.address  %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Created Date</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.created_at.strftime('%Y/%m/%d') %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Created User</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.created_user.name %></label>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label">Updated date</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.updated_at.strftime('%Y/%m/%d') %></label>
                </div>
            </div>
            <div class="row">
                <label class="col-sm-4 col-form-label">Updated User</label>
                <div class="col-sm-8">
                    <label class="col-sm-10 col-form-label"><%= @user.updated_user.name %></label>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/users/change_password.html.erb
<div class="card">
  <h3 class="card-header">Change Password</h3>
  <div class="card-body">
<%= form_with :url => update_password_user_path do |form| %>
            <div class="field form-group row">
                <%= form.label :current_password, class:"col-sm-2 col-form-label" %>
                <%= form.password_field :password, class:"form-control col-sm-5", :required => 'true'%>
            </div>
            <br/>
            <div class="field form-group row">
                <%= form.label :new_password, class:"col-sm-2 col-form-label" %>
                <%= form.password_field :new_password, class:"form-control col-sm-5", :required => 'true'%>
            </div>
            <br/>
            <div class="field form-group row">
                <%= form.label :confirm_new_password, class:"col-sm-2 col-form-label" %>
                <%= form.password_field :new_password_confirmation, class:"form-control col-sm-5", :required => 'true'%>
            </div><br/>
            <div class="form-group row">
                <div class="col-sm-7">
                    <%= form.submit "Update Password", class: 'btn btn-secondary' %>
                </div>
            </div>
        <% end %>
  </div>
</div>

<style>
.card_option{
    width: 50rem;
    margin: 0 auto;
}
</style>

app/views/users/create_confirm.html.erb
<div class="card">
  <h3 class="card-header">Confirm User</h3>
  <div class="card-body">
<%= form_with model: @user do |form| %>

  <div class="field form-group row">
    <%= form.label :name, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :name, class:"form-control col-sm-5",:value => @user.name, :readonly => true %>
  </div>

  <div class="field form-group row">
    <%= form.label :email_address, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :email, class:"form-control col-sm-5", :value => @user.email, :readonly => true  %>
  </div>

  <div class="field form-group row">
    <%= form.label :password, class:"col-sm-2 col-form-label" %>
    <%= form.password_field :password, class:"form-control col-sm-5", :value => @user.password, :readonly => true  %>
  </div>

  <div class="field form-group row">
    <%= form.label :confirm_password, class:"col-sm-2 col-form-label" %>
    <%= form.password_field :password_confirmation, class:"form-control col-sm-5", :value => @user.password_confirmation, :readonly => true  %>
  </div>

  <div class="field form-group row">
    <%= form.label :Type, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :role, :value => Constants::TYPES.keys[@user.role.to_i], :readonly => true, class:"form-control col-sm-5"%>
  </div>

  <div class="field form-group row">
    <%= form.label :phone, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :phone, class:"form-control col-sm-5", :value => @user.phone, :readonly => true  %>
  </div>

  <div class="field form-group row">
    <%= form.label :date_of_birth, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :dob, class:"form-control col-sm-5", :value => @user.dob, :readonly => true  %>
  </div>

  <div class="field form-group row">
    <%= form.label :address, class:"col-sm-2 col-form-label" %>
    <%= form.text_area :address, class:"form-control col-sm-5", :value => @user.address, :readonly => true  %>
  </div>

    <div class="field form-group row">
    <%= form.label :profile, class:"col-sm-2 col-form-label" %>
    <%= image_tag @user.profile, class:"form-control col-sm-5", style: 'height:500px;width:auto;' %>
    <%= form.hidden_field :profile, :value => @user.profile%>
  </div>

  <%= form.hidden_field :create_user_id, :value => @user.create_user_id%>
  <%= form.hidden_field :updated_user_id, :value => @user.updated_user_id%>

  <div class="actions">
    <%= form.submit "Create", class:"btn btn-secondary" %>
    <%= link_to 'Cancel', users_path , class:"btn btn-dark" %>
  </div>
  
<% end %>
  </div>
</div>

app/views/users/edit_profile.html.erb
<div class="card">
  <h3 class="card-header">Edit Profile</h3>
  <div class="card-body">
<%= form_with model: @profile_form, url: update_profile_user_path(@profile_form.id) do |form| %>

  <div class="field form-group row">
    <%= form.label :name, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :name, class:"form-control col-sm-5",:value => @profile_form.name %>
    <% if @profile_form.errors[:name].any? %>
      <span style="color:red;">Name <%= @profile_form.errors[:name][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :email_address, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :email, class:"form-control col-sm-5", :value => @profile_form.email %>
    <% if @profile_form.errors[:email].any? %>
      <span style="color:red;">Email <%= @profile_form.errors[:email][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :Type, class:"col-sm-2 col-form-label" %>
    <%= form.select(:role, options_for_select(Constants::TYPES, selected: @profile_form.role.to_i), {}, {:class => "form-control col-sm-5"}) %>
    <% if @profile_form.errors[:role].any? %>
      <span style="color:red;">Role <%= @profile_form.errors[:role][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :phone, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :phone, class:"form-control col-sm-5", :value => @profile_form.phone  %>
    <% if @profile_form.errors[:phone].any? %>
      <span style="color:red;">Phone <%= @profile_form.errors[:phone][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :date_of_birth, class:"col-sm-2 col-form-label" %>
    <%= form.date_field :dob, class:"form-control col-sm-5", :value => @profile_form.dob  %>
    <% if @profile_form.errors[:dob].any? %>
      <span style="color:red;">Date Of Birth <%= @profile_form.errors[:dob][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :address, class:"col-sm-2 col-form-label" %>
    <%= form.text_area :address, class:"form-control col-sm-5", :value => @profile_form.address  %>
        <% if @profile_form.errors[:address].any? %>
      <span style="color:red;">Address <%= @profile_form.errors[:address][0] %>
    <% end %>
  </div>

    <div class="field form-group row">
    <%= form.label :old_profile, class:"col-sm-2 col-form-label" %>
    <%= image_tag @profile_form.profile, class:"form-control col-sm-2", style: 'height:150px;width:auto;' %>
    <% if @profile_form.errors[:profile].any? %>
      <span style="color:red;">Profile <%= @profile_form.errors[:profile][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :new_profile, class:"col-sm-2 col-form-label" %>
    <%= form.file_field :new_profile, class:"form-control col-sm-5", :accept => "image/x-png,image/gif,image/jpeg" %>
  </div>
  <%= form.hidden_field :profile, :value =>@profile_form.profile%>
  <%= form.hidden_field :id, :value =>@profile_form.id%>
  <% if current_admin.present? %>
    <%= form.hidden_field :updated_user_id, :value => current_admin.id %>
  <% else %>
    <%= form.hidden_field :updated_user_id, :value => current_user.id %>
  <% end %>

  <div class="actions">
    <%= form.submit "Edit", class:"btn btn-secondary" %>
    <input type="reset" value="Clear" class="btn btn-dark">
    <%= link_to  "Change Password", change_password_user_path(id: @profile_form.id) %>
    <a href=>
  </div>
  
<% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="card">
  <h3 class="card-header">User List</h3>
  <div class="card-body">
  <%= form_tag({ :action => :search_user }, { :method => :get }) do %>
      <div class="field form-group row">
          <label class="col-sm-1 col-form-label">Name:</label>
          <%= text_field_tag :name, params[:name], class: "form-control col-sm-2" %>

          <label class="col-sm-1 col-form-label">Email:</label>
          <%= text_field_tag :email, params[:email], class: "form-control col-sm-2" %>

          <label class="col-sm-1 col-form-label">From:</label>
          <%= date_field_tag :from_date, params[:from_date], autocomplete: 'off', class: "form-control col-sm-2" %>

          <label class="col-sm-1 col-form-label">To:</label>
          <%= date_field_tag :to_date, params[:to_date], autocomplete: 'off', class: "form-control col-sm-2" %>
      </div>
      <div class="actions">
          <%= submit_tag ("Search"), class: 'btn btn-secondary float-right' %>
          <input type="reset" value="Clear" class="btn btn-dark float-right mb-3 mr-3">
      </div>
  <% end %>
  <div class="table_container">
    <table id="dtBasicExample" class="table table-bordered table-sm" cellspacing="0">
      <thead class="thead-light">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Created User</th>
          <th>Type</th>
          <th>Phone</th>
          <th>Date of Birth</th>
          <th>Address</th>
          <th>Created Date</th>
          <th>Updated Date</th>
          <% if current_admin.present? %>          
          <th>Operation</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td></td>
            <td><%= link_to user.name, user_path(user), {:remote => true, 'data-toggle' =>  "modal"} %></td>
            <td><%= user.email %></td>
            <td><%= user.created_user.name %></td>
            <td><%= user.role == '0' ? 'Admin' : 'User' %></td>
            <td><%= user.phone %></td>
            <td><%= user.dob.strftime('%Y/%m/%d') if user.dob.present? %></td>
            <td><%= user.address %></td>
            <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= user.updated_at.strftime('%Y/%m/%d') %></td>
            <% if current_admin.present? %>
              <td><%= link_to 'Delete', '#', "data-toggle"=>"modal", "data-target" => "#deleteuser_#{user.id}", :class=>'btn btn-danger' %>
              <div class="modal fade" id="deleteuser_<%= user.id %>">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                  <h5 class="modal-title">User Detete Confirmation</h5>
                    </div>
                    <div class="modal-body">
                      <p>Are you sure to delete?</p>
                    </div>
                      <div class="modal-footer">
                        <a href="#" data-dismiss="modal" class="btn btn-info">Cancel</a>
                        <%= link_to 'Delete', user_path(user), method: :delete, :class => 'btn btn-danger' %>
                      </div>
                  </div>
                </div>
              </div>
              </td>
            <% end %>          
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
  </div>
</div>

<div id="userDetail" class="modal fade" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:700px"></div>
  </div>
</div>
<style>
#dtBasicExample {
    counter-reset: tableCount;     
}
.counterCell:before {              
    content: counter(tableCount); 
    counter-increment: tableCount; 
}
</style>
<script>
$(document).ready(function () {
      var dataTable = null

    document.addEventListener("turbolinks:before-cache", function() {
      if (dataTable !== null) {
      dataTable.destroy()
      dataTable = null
      }
    })
  dataTable = $('#dtBasicExample').DataTable({
    "searching": false,
    "ordering": false,
    "bLengthChange": false,
    "info": false,
    "pageLength": 5,
  });
  dataTable.column(0).nodes().each( function (cell, i) {
      cell.innerHTML = i+1;
  });
  $('.dataTables_length').addClass('bs-select');
});
</script>

app/views/users/new.html.erb
<div class="card">
  <h3 class="card-header">Add User</h3>
  <div class="card-body">
    <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="card">
  <h3 class="card-header">Profile</h3>
  <div class="card-body">
<div class="row p-3">
    <div class="col-4">
        <div class="form-group">
            <div class="img text-center "><%= image_tag @user.profile, style: 'height:120px;width:auto;' %> </div>
        </div>
    </div>
    <div class="col-8">
        <div class="col-8">
        <div class="form-group row mb-3">
            <div class="col-sm-4"> Name </div>
            <div class="col-sm-8"><%= @user.name %></div>
        </div>
        <div class="form-group row mb-3">
            <div class="col-sm-4"> Type </div>
            <div class="col-sm-8"><%= Constants::TYPES.keys[@user.role.to_i] %></div>
        </div>
        <div class="form-group row mb-3">
            <div class="col-sm-4"> Email </div>
            <div class="col-sm-8"><%= @user.email %></div>
        </div>
        <div class="form-group row mb-3">
            <div class="col-sm-4"> Phone </div>
            <div class="col-sm-8"><%= @user.phone %></div>
        </div>
        <div class="form-group row mb-3">
            <div class="col-sm-4"> Date of Birth </div>
            <div class="col-sm-8"><%= @user.dob %></div>
        </div>
        <div class="form-group row mb-3">
            <div class="col-sm-4"> Address </div>
            <div class="col-sm-8"><%= @user.address %></div>
        </div>
        <a class="btn btn-dark" href="<%= edit_profile_user_path(@user) %>">Edit Profile</a>
    </div>
</div>
  </div>
</div>

app/views/users/show.js.erb
$("#userDetail").find(".modal-content").html("<%= j (render 'show') %>");
$("#userDetail").modal('show');