config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  #get 'login/login'
  resources :users do
    collection do
      post :create_confirm
      get :create_confirm, to: "users#new"
      get :search_user
    end
    member do
      get :profile, to: "users#profile"
      get :edit_profile, to: "users#edit_profile"
      post :update_profile
      get :update_profile, to: "users#edit_profile"
      get :change_password
      post :update_password
    end
  end

  resources :posts do
    collection do
      post :post_create_confirm
      get :post_create_confirm, to: "posts#new"
      get :search_post
      get :upload_csv
      post :import_csv
      get :download
    end
    member do
      get :update_confirm, to: "posts#update_confirm"
      post :update_confirm
      post :update_post
    end
  end
  resources :password_resets
  
  get 'users/new'
  get 'login', to: 'login#login'
  post 'login', to: 'login#userlogin'
  get 'logout', to: 'login#logout'
  get '/sign_up', to: 'login#sign_up'
  post '/sign_up', to: 'login#create_account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  # Show login page
  def login
    cookies.delete(:user_id)
    cookies.delete(:admin_id)
  end

  # function : userlogin
  # params : email, password
  def userlogin

    #find user by email
    @user = UserService.find_by_email(params[:email])

    #check validation for email and password
    if params[:email].blank? && params[:password].blank?
      redirect_to login_path, notice: Messages::EMAIL_AND_PASSWORD_REQUIRE_VALIDATION
    elsif params[:email].blank? && params[:password]!=nil
      redirect_to login_path, notice: Messages::EMAIL_REQUIRE_VALIDATION
    elsif params[:email]!=nil && params[:password].blank?
      redirect_to login_path, notice: Messages::PASSWORD_REQUIRE_VALIDATION
    elsif @user && @user.authenticate(params[:password])
      token = encode_token({user_id: @user.id})
      if params[:remember_me]
        if @user.role == '0'
          cookies.permanent[:admin_id] = @user.id
        elsif @user.role == '1'
          cookies.permanent[:user_id] = @user.id
        end
      else
        if @user.role == '0'
          cookies[:admin_id] = { :value => token, :expires => Time.now + 3600 }
        elsif @user.role == '1'
          cookies[:user_id] = { :value => token, :expires => Time.now + 3600 }
        end
      end
      # go to user list
      redirect_to users_path, notice: Messages::SUCCESSFUL_LOG_IN
    else
      # go to login page   
      redirect_to login_path, notice: Messages::INVALID_EMAIL_OR_PASSWORD
    end
  end

  #function : logout
  def logout
    cookies.delete(:user_id)
    cookies.delete(:admin_id)
    # go to login page
    redirect_to login_path
  end

  # function : sign_up
  # show sign up form page
  # return : @user
  def sign_up
    cookies.delete(:user_id)
    cookies.delete(:admin_id)
    @user = User.new
  end

  # function : create_account
  # create user account
  # params : user_params
  def create_account
    @user = User.new(user_params)
    if @user.valid? && user_params.has_key?(:profile)
      dir = "#{Rails.root}/app/assets/profiles"
      FileUtils.mkdir_p(dir) unless File.directory?(dir)
      profileName = user_params[:name] + "_" + Time.now.strftime('%Y%m%d_%H%M%S') +"." + ActiveStorage::Filename.new(user_params[:profile].original_filename).extension
      File.open(Rails.root.join('app/assets/', 'images', profileName), 'wb') do |f|
        f.write(user_params[:profile].read)
      end
      @user.profile = profileName
    end
    if !@user.valid?
      render :sign_up
    elsif UserService.createUser(@user)
      @login_user = UserService.find_by_email(@user.email)
      cookies[:user_id] = @login_user.id
      redirect_to users_path, notice: Messages::SUCCESSFUL_SIGN_UP
    else
      render :sign_up
    end
  end
   
  private

    # User params
    def user_params
      params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :role, :phone, :dob, :profile, :create_user_id, :updated_user_id)
    end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/login.html.erb
<div class="pt-5">
  <h1 class="text-center">Log In</h1>
    <div class="container">
        <div class="row">                     
            <div class = "card col-md-5 mx-auto round_corner">
                <div class="card-body">
                                            
                    <%= form_tag login_path do %>
                        <div class="form-group required">
                            <label for="email">Email</label>
                            <%= text_field_tag :email, params[:email], class: 'form-control' %>
                        </div>                    
                        <div class="form-group required">
                            <label class="d-flex flex-row align-items-center" for="password">Password 
                                <a class="ml-auto border-link small-xl" href="<%= password_resets_new_path %>">Forget?</a></label>
                            <%= password_field_tag :password ,params[:password_digest], class: 'form-control'%>
                        </div>
                        <div class="form-group mt-4 mb-4">
                            <div class="custom-control custom-checkbox">
                                <%= check_box_tag :remember_me, 1, params[:remember_me], class: "custom-control-input", id: "remember-me", name: "remember-me" %>
                                <label class="custom-control-label" for="remember-me">Remember me?</label>
                            </div>
                        </div>
                        <div class="form-group pt-1">
                            <button class="btn btn-primary btn-block" type="submit">Log In</button>
                        </div>
                    </form>
                    <p class="small-xl pt-3 text-center">
                        <span class="text-muted">Not a member?</span>
                        <%= link_to "Sign up", sign_up_path %>
                    </p>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/login/sign_up.html.erb
<div class="pt-3">
  <h1 class="text-center">Sign Up</h1>
<div class="container">
                <div class="row">
                       
                      
                    <div class = "card col-md-5 mx-auto round_corner">
                      <div class="card-body">
                                                  
                                <%= form_with model: @user, url: '/sign_up', method: :post do |form| %>
                                <div class="form-group required"> 
                                    <%= image_tag 'default.jpg', id: "profile", class: "d-flex justify-content-center rounded-circle mb-3" %>
                                    <label for="profile">Profile</label>
                                    <% if @user.errors[:profile].any? %>
                                    <span class="error">Profile <%= @user.errors[:profile][0] %></span>
                                    <% end %>
                                    <%= form.file_field :profile, :onchange => "readURL(this);" ,class: "form-control" , :accept => "image/x-png,image/gif,image/jpeg" %>
                                </div>
                                <div class="form-group required">
                                    <label for="username">Name</label>                                        
                                    <% if @user.errors[:name].any? %>
                                        <span class="error">Name <%= @user.errors[:name][0] %></span>
                                    <% end %>
                                    <%= form.text_field :name, class: 'form-control' %>
                                </div>
                                <div class="form-group required">
                                    <label for="email">Email</label>
                                    <% if @user.errors[:email].any? %>
                                        <span class="error">Email <%= @user.errors[:email][0] %></span>
                                    <% end %>     
                                    <%= form.text_field :email, class: 'form-control' %>
                                </div>           
                                <div class="form-group required">
                                    <label for="password">Password</label>
                                    <% if @user.errors[:password].any? %>
                                    <span class="error">Password <%= @user.errors[:password][0] %></span>
                                    <% end %>
                                    <%= form.password_field :password, class: 'form-control'%>
                                </div>
                                <div class="form-group pt-1">
                                    <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
                                </div>
                                <%= form.hidden_field :role, value: "1" %>
                                <%= form.number_field :create_user_id, value: 1, type: :hidden %>
                                <%= form.number_field :updated_user_id, value: 1, type: :hidden %>
                            </form>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
</div>

<style>
#profile {
    height: 150px;
    width: 150px;
    margin: auto;
}
.error {
    color: red;
    float: right;
}
</style>
<script>
function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#profile')
                        .attr('src', e.target.result)
                        .width(150)
                        .height(150);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
</script>