config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  #get 'login/login'
  resources :users do
    collection do
      post :create_confirm
      get :create_confirm, to: "users#new"
      get :search_user
    end
    member do
      get :profile, to: "users#profile"
      get :edit_profile, to: "users#edit_profile"
      post :update_profile
      get :update_profile, to: "users#edit_profile"
      get :change_password
      post :update_password
    end
  end

  resources :posts do
    collection do
      post :post_create_confirm
      get :post_create_confirm, to: "posts#new"
      get :search_post
      get :upload_csv
      post :import_csv
      get :download
    end
    member do
      get :update_confirm, to: "posts#update_confirm"
      post :update_confirm
      post :update_post
    end
  end
  resources :password_resets
  
  get 'users/new'
  get 'login', to: 'login#login'
  post 'login', to: 'login#userlogin'
  get 'logout', to: 'login#logout'
  get '/sign_up', to: 'login#sign_up'
  post '/sign_up', to: 'login#create_account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :created_user, class_name: "User", foreign_key: "create_user_id"
    belongs_to :updated_user, class_name: "User", foreign_key: "updated_user_id"
  
    validates :title, presence: true
    validates :description, presence: true

    def self.to_csv
        attributes = Constants::HEADER    
        CSV.generate(headers: true) do |csv|
          csv << attributes    
          all.each do |post|
            csv << attributes.map{ |attr| post.send(attr) }
          end
        end
    end

    def self.import(file,create_user_id,updated_user_id)        
        CSV.foreach(file.path, headers: true,encoding:'iso-8859-1:utf-8',:quote_char => "|", header_converters: :symbol) do |row|            
            Post.create! row.to_hash.merge(create_user_id: create_user_id, updated_user_id: updated_user_id)
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authorized

    # function : index
    # show post list
    # return : @posts
    def index
        @posts = PostService.getAllPosts
    end

    # function : new
    # show new post create page
    # return : @post
    def new
        @post = Post.new()
    end

    # function : show
    # show post detail
    # params : post_id
    # return : @post
    def show
        @post = PostService.getPostById(params[:id])    
    end

    # function : edit
    # show edit post page
    # params : id
    # return : @post_form
    def edit
        @post = PostService.getPostById(params[:id])
        @post_form = PostForm.new(PostForm.initialize(@post))
    end

    # function : update_fonfirm
    # confirm post update
    # params : post_form_params
    # return @post_form
    def update_confirm
        @post_form = PostForm.new(post_form_params)
        unless @post_form.valid?
            render :edit
        end
    end

    # function : update_post
    # update post
    # params : post_form_params
    def update_post
        isPostUpdate = PostService.updatePost(post_form_params)
        if isPostUpdate
            redirect_to posts_path
        else 
            render :edit
        end
    end

    # function : search post
    # search posts by keyword
    # params : keyword
    # return : @posts
    def search_post
        @keyword=params[:keyword]
        @posts = PostService.searchPost(@keyword)
        render :index
    end

    # function : post_create_confirm
    # confirm post create
    # params : post_params
    # return : @post
    def post_create_confirm
        @post = Post.new(post_params)
        unless @post.valid?
            render :new
        end
    end

    # function : create
    # Create post
    # params : post_param
    def create
        isSavePost = PostService.createPost(post_params)
        if isSavePost
          redirect_to posts_path
        else
          render :new
        end
    end

    # function : destroy
    # delete post
    # params : post id
    def destroy
        if current_admin.present?            
            PostService.deletePost(params[:id],current_admin[:id])
        else            
            PostService.deletePost(params[:id],current_user[:id])
        end
        redirect_to posts_path
    end

    # function : import_csv
    # upload post csv file
    # params : file
    def import_csv
        if current_admin.present? 
            updated_user_id = current_admin.id
            create_user_id = current_admin.id
        else
            updated_user_id = current_user.id
            create_user_id = current_user.id
        end
        if (params[:file].nil?)
            redirect_to upload_csv_posts_path, notice: Messages::REQUIRE_FILE_VALIDATION        
        elsif !File.extname(params[:file]).eql?(".csv")
            redirect_to upload_csv_posts_path, notice: Messages::WRONG_FILE_TYPE  
        else
            error_msg = PostsHelper.check_header(Constants::HEADER,params[:file])
            if error_msg.present?
                redirect_to upload_csv_posts_path, notice: error_msg
            else 
                Post.import(params[:file],create_user_id,updated_user_id)
                redirect_to posts_path, notice: Messages::UPLOAD_SUCCESSFUL
            end
        end
    end

    # function : download
    # down post list
    # return : Post List.csv
    def download
        @posts = PostService.getAllPosts
        respond_to do |format|
            format.html
            format.csv { send_data @posts.to_csv,  :filename => "Post List.csv" }
          end
    end

    private

    # set post parameters
    def post_params
      params.require(:post).permit(:id, :title, :description, :status, :create_user_id, :updated_user_id)
    end

    # set post form parameters
    def post_form_params
        params.require(:post_form).permit(:id, :title, :description, :status, :updated_user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def self.check_header(expected_header,csv_file)
        header = CSV.open(csv_file, 'r') { |csv| csv.first }
        error_msg = "" 
        for i in (0..header.size-1)
          if header[i].downcase != expected_header[i].downcase
            error_msg = Messages::WRONG_HEADER
          elsif (header.size != 3)
            error_msg = Messages::WRONG_COLUMN
          end
        end
      return error_msg
    end
end

app/views/posts/_show.html.erb
<div class="modal-header">
<h5 class="modal-title" id="exampleModalLabel">Post Detail</h5>
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>
<div class="modal-body">
	<form>
      	<div class="form-group row">
            <label class="col-sm-4 col-form-label">Title</label>
            <div class="col-sm-8">
                <label class="col-sm-10 col-form-label"><%= @post.title  %></label>
            </div>
        </div>
      	<div class="form-group row">
            <label class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
                <label class="col-sm-10 col-form-label"><%= @post.description  %></label>
            </div>
        </div>
      	<div class="form-group row">
            <label class="col-sm-4 col-form-label">Status</label>
            <div class="col-sm-8">
                <label class="col-sm-10 col-form-label"><%= @post.status == 1  ? 'Active' : 'Inactive' %></label>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">Posted at</label>
            <div class="col-sm-8">
                <label class="col-sm-10 col-form-label"><%= @post.created_at.strftime('%Y/%m/%d') %></label>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">Posted User</label>
            <div class="col-sm-8">
                <label class="col-sm-10 col-form-label"><%= @post.created_user.name %></label>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">Updated at</label>
            <div class="col-sm-8">
                <label class="col-sm-10 col-form-label"><%= @post.updated_at.strftime('%Y/%m/%d') %></label>
            </div>
        </div><div class="form-group row">
            <label class="col-sm-4 col-form-label">Updated User</label>
            <div class="col-sm-8">
                <label class="col-sm-10 col-form-label"><%= @post.updated_user.name %></label>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>

app/views/posts/edit.html.erb
<div class="card">
  <h3 class="card-header">Edit Post</h3>
  <div class="card-body">
<%= form_with model: @post_form, :url => update_confirm_post_path(@post_form.id) do |form| %>

  <div class="field form-group row">
    <%= form.label :title, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :title, class:"form-control col-sm-5" %>
    <% if @post_form.errors[:title].any? %>
      <span style="color:red;">Title <%= @post_form.errors[:title][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :description, class:"col-sm-2 col-form-label" %>
    <%= form.text_area :description, class:"form-control col-sm-5" %>
    <% if @post_form.errors[:description].any? %>
      <span style="color:red;">Description <%= @post_form.errors[:description][0] %>
    <% end %>
  </div>
  <div class="field form-group row">
  <%= form.label :status, class:"col-sm-2 col-form-label" %>
    <div class="custom-switch align-self-center">
        <%= form.check_box :status, class:"custom-control-input", id: "customSwitch1" %>
        <label class="custom-control-label" for="customSwitch1"></label>
    </div>
  </div>

  
  <%= form.hidden_field :id, :value =>@post_form.id %>
  <% if current_admin.present? %>
    <%= form.hidden_field :updated_user_id, :value => current_admin.id %>
    <%= form.hidden_field :create_user_id, :value => current_admin.id %>
  <% else %>
    <%= form.hidden_field :updated_user_id, :value => current_user.id %>
    <%= form.hidden_field :create_user_id, :value => current_user.id %>
  <% end %>


  <div class="actions">
    <%= form.submit "Edit", class:"btn btn-secondary" %>
    <input type="reset" value="Clear" class="btn btn-dark">
  </div>
  
<% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="card">
  <h3 class="card-header">Post List</h3>
  <div class="card-body">
  <%= form_tag({ :action => :search_post }, { :method => :get }) do %>
      <div class="field form-group row float-right">
          <label class="col-form-label mr-2">Keyword:</label>
          <%= text_field_tag :keyword, params[:keyword], class: "form-control col-sm-3 mr-2" %>
          <%= submit_tag ("Search"), class: 'btn btn-primary mr-2' %>
          <%= link_to "Create", new_post_path,  class: 'btn btn-primary mr-2' %>
          <%= link_to "Upload", upload_csv_posts_path, class: 'btn btn-primary mr-2' %>
          <%= link_to "Download", download_posts_path(format: :csv), class: 'btn btn-primary' %>
      </div>
  <% end %>
<div class="table_container">
  <table id="list" class="table table-bordered table-sm" cellspacing="0">
    <thead class="thead-light">
      <tr>
        <th>Post Title</th>
        <th>Post Description</th>
        <th>Posted User</th>
        <th>Posted Date</th>
        <th>Operation</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, post_path(post), {:remote => true, 'data-toggle' =>  "modal"} %></td>
          <td><%= post.description %></td>
          <td><%= post.created_user.name %></td>
          <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
          <% if current_user.present? %>
            <% if current_user.name == post.created_user.name %>
              <td><%= link_to "Edit",edit_post_path(post), class: 'btn btn-primary mr-2'  %>
              <%= link_to 'Delete', '#', "data-toggle"=>"modal", "data-target" => "#deletepost_#{post.id}",:class=>'btn btn-danger' %></td>
              <% else %>
              <td></td>
            <% end %>
          <% else %>
            <td><%= link_to "Edit",edit_post_path(post), class: 'btn btn-primary mr-2'  %>
            <%= link_to 'Delete', '#', "data-toggle"=>"modal", "data-target" => "#deletepost_#{post.id}",:class=>'btn btn-danger' %></td>
          <% end %>
          <div class="modal fade" id="deletepost_<%= post.id %>">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                  <h5 class="modal-title">Post Detete Confirmation</h5>
                    </div>
                    <div class="modal-body">
                      <p>Are you sure to delete?</p>
                    </div>
                      <div class="modal-footer">
                        <a href="#" data-dismiss="modal" class="btn btn-info">Cancel</a>
                        <%= link_to 'Delete', post_path(post), method: :delete, :class => 'btn btn-danger' %>
                      </div>
                  </div>
                </div>
              </div>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
  </div>
</div>

<div id="postDetail" class="modal fade" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:700px"></div>
  </div>
</div>
<script>
$(document).ready(function () {
      var dataTable = null

    document.addEventListener("turbolinks:before-cache", function() {
      if (dataTable !== null) {
      dataTable.destroy()
      dataTable = null
      }
    })
  dataTable = $('#list').DataTable({
    "searching": false,
    "ordering": false,
    "bLengthChange": false,
    "info": false,
    "pageLength": 5,
  }).draw();
  $('.dataTables_length').addClass('bs-select');
});
</script>

app/views/posts/new.html.erb
<div class="card">
  <h3 class="card-header">Create Post</h3>
  <div class="card-body">
<%= form_with model: @post, url: post_create_confirm_posts_path(@post) do |form| %>

  <div class="field form-group row">
    <%= form.label :title, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :title, class:"form-control col-sm-5" %>
    <% if @post.errors[:title].any? %>
      <span style="color:red;">Title <%= @post.errors[:title][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :description, class:"col-sm-2 col-form-label" %>
    <%= form.text_area :description, class:"form-control col-sm-5" %>
    <% if @post.errors[:description].any? %>
      <span style="color:red;">Description <%= @post.errors[:description][0] %>
    <% end %>
  </div>
  <% if current_admin.present? %>
    <%= form.hidden_field :updated_user_id, :value => current_admin.id %>
    <%= form.hidden_field :create_user_id, :value => current_admin.id %>
  <% else %>
    <%= form.hidden_field :updated_user_id, :value => current_user.id %>
    <%= form.hidden_field :create_user_id, :value => current_user.id %>
  <% end %>

  <div class="actions">
    <%= form.submit "Create", class:"btn btn-secondary" %>
    <input type="reset" value="Clear" class="btn btn-dark">
  </div>
  
<% end %>
  </div>
</div>

app/views/posts/post_create_confirm.html.erb
<div class="card">
  <h3 class="card-header">Confirm Post</h3>
  <div class="card-body">
<%= form_with model: @post do |form| %>

  <div class="field form-group row">
    <%= form.label :title, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :title, class:"form-control col-sm-5", readonly: 'true' %>
    <% if @post.errors[:title].any? %>
      <span style="color:red;">Title <%= @post.errors[:title][0] %>
    <% end %>
  </div>

  <div class="field form-group row">
    <%= form.label :description, class:"col-sm-2 col-form-label" %>
    <%= form.text_area :description, class:"form-control col-sm-5", readonly: 'true' %>
    <% if @post.errors[:description].any? %>
      <span style="color:red;">Description <%= @post.errors[:description][0] %>
    <% end %>
  </div>

  <% if current_admin.present? %>
    <%= form.hidden_field :updated_user_id, :value => current_admin.id %>
    <%= form.hidden_field :create_user_id, :value => current_admin.id %>
  <% else %>
    <%= form.hidden_field :updated_user_id, :value => current_user.id %>
    <%= form.hidden_field :create_user_id, :value => current_user.id %>
  <% end %>

  <div class="actions">
    <%= form.submit "Create", class:"btn btn-secondary" %>
    <%= link_to "Cancel", 'javascript:history.go(-1);', class: 'btn btn-dark' %>
  </div>
  
<% end %>
  </div>
</div>

app/views/posts/show.js.erb
$("#postDetail").find(".modal-content").html("<%= j (render 'show') %>");
$("#postDetail").modal('show');

app/views/posts/update_confirm.html.erb
<div class="card">
  <h3 class="card-header">Confirm Post</h3>
  <div class="card-body">
<%= form_with scope: @post_form, url: update_post_post_path(@post_form.id) do |form| %>
  <% if @post_form.errors.any? %>
      <ul>
        <% @post_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
  <% end %>

  <div class="field form-group row">
    <%= form.label :title, class:"col-sm-2 col-form-label" %>
    <%= form.text_field :title, class:"form-control col-sm-5", :readonly => true %>
  </div>

  <div class="field form-group row">
    <%= form.label :description, class:"col-sm-2 col-form-label" %>
    <%= form.text_area :description, class:"form-control col-sm-5", :readonly => true %>
  </div>
  <div class="field form-group row">
  <%= form.label :status, class:"col-sm-2 col-form-label" %>
    <div class="custom-switch align-self-center">
        <%= form.check_box :status, class:"custom-control-input", id: "customSwitch1", :disabled => 'true'%>
        <label class="custom-control-label" for="customSwitch1"></label>
    </div>
  </div>

  <%= form.hidden_field :status %>
  <%= form.hidden_field :id, :value =>@post_form.id%>
  <% if current_admin.present? %>
    <%= form.hidden_field :updated_user_id, :value => current_admin.id %>
    <%= form.hidden_field :create_user_id, :value => current_admin.id %>
  <% else %>
    <%= form.hidden_field :updated_user_id, :value => current_user.id %>
    <%= form.hidden_field :create_user_id, :value => current_user.id %>
  <% end %>

  <div class="actions">
    <%= form.submit "Update", class:"btn btn-secondary" %>
    <%= link_to "Back", 'javascript:history.go(-1);', class: 'btn btn-dark' %>
  </div>
  
<% end %>
  </div>
</div>

app/views/posts/upload_csv.html.erb
<div class="card">
  <h3 class="card-header">Upload CSV</h3>
  <div class="card-body">
<%= form_tag import_csv_posts_path, multipart: true do |form| %>

  <div class="field form-group row">
    <div class="col-sm-2 col-form-label text-end"> CSV file </div>
    <div class="col-sm-5"><%= file_field_tag :file, accept: 'text/csv', class: "form-control" %></div>
  </div>

  <div class="actions">
    <%= submit_tag "Upload", class: 'btn btn-secondary' %>
    <%= button_tag "Clear", class: 'btn btn-dark', type: :reset %>
  </div>
  
<% end %>
</div>