config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  #get 'login/login'
  resources :users do
    collection do
      post :create_confirm
      get :create_confirm, to: "users#new"
      get :search_user
    end
    member do
      get :profile, to: "users#profile"
      get :edit_profile, to: "users#edit_profile"
      post :update_profile
      get :update_profile, to: "users#edit_profile"
      get :change_password
      post :update_password
    end
  end

  resources :posts do
    collection do
      post :post_create_confirm
      get :post_create_confirm, to: "posts#new"
      get :search_post
      get :upload_csv
      post :import_csv
      get :download
    end
    member do
      get :update_confirm, to: "posts#update_confirm"
      post :update_confirm
      post :update_post
    end
  end
  resources :password_resets
  
  get 'users/new'
  get 'login', to: 'login#login'
  post 'login', to: 'login#userlogin'
  get 'logout', to: 'login#logout'
  get '/sign_up', to: 'login#sign_up'
  post '/sign_up', to: 'login#create_account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert" style="width:1140px;">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div class="footer text-center py-3 bg-light">
        <a href="http://seattleconsultingmyanmar.com/en">Seattle Consulting Myanmar Co.,Ltd. All rights reserved. © Copyright</a>
    </div>
</footer>

<style>
.footer {
  bottom: 0;
  width: 100%;
}

</style>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">BulletinBoard</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to "User List", users_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Post List", posts_path , class:"nav-link" %>
        </li>          
    </ul>
    <ul class="navbar-nav my-sm-0">
    <% if current_admin.present? %>
      <li class="nav-item">
        <%= link_to "Create User", new_user_path , class:"nav-link" %>
      </li>
    <% end %>
      <li class="nav-item">
      <div class="dropdown show">
        <% if current_admin.present? %>
          <a class="nav-link dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_admin.name %>
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="left:-65px;">
            <a class="dropdown-item" href="/users/<%= current_admin.id %>/profile">Profile</a>
            <%= link_to "Log Out", logout_path , class:"dropdown-item" %>
          </div>
        <% else %>
          <a class="nav-link dropdown-toggle" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="left:-76px;">
            <a class="dropdown-item" href="/users/<%= current_user.id %>/profile">Profile</a>
            <%= link_to "Log Out", logout_path , class:"dropdown-item" %>
          </div>        
      <% end %>
      </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BulletinBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js"></script>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Data Table -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>


  </head>

  <body>
    <% if logged_in? %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>
<style>
body{
  background: #98AFC7 !important;
  font-family: 'Muli', sans-serif;
  
}

.card {
  width: 1140px;
}

table {
  table-layout:fixed;
}

.round_corner{
  border-radius : 10px;
  box-shadow: 10px 10px 10px 10px rgb(0 0 0 / 20%)
}
</style>